### ISSUE TITLE
i have a huge issue

### ISSUE THREAD

**Issue by kessanro** [sambeyer/soundcloudbot#1]
error:

TypeError: bot.reply is not a function
    at Client.<anonymous> (C:\Users\User\Desktop\bot\index.js:329:7)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at MessageCreateHandler.handle (C:\Users\User\Desktop\bot\node_modules\disco
rd.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\User\Desktop\bot\node_modules\dis
cord.js\src\client\websocket\packets\WebSocketPacketManager.js:93:65)
    at WebSocketManager.eventMessage (C:\Users\User\Desktop\bot\node_modules\dis
cord.js\src\client\websocket\WebSocketManager.js:198:31)
    at WebSocket.ws.onmessage (C:\Users\User\Desktop\bot\node_modules\discord.js
\src\client\websocket\WebSocketManager.js:74:37)
    at WebSocket.onMessage (C:\Users\User\Desktop\bot\node_modules\ws\lib\WebSoc
ket.js:442:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
i need help

**Comment by sambeyer** [comment]
Hi Kessanro, unfortunately I stopped working on this project a little while ago, and I'm quite busy at the moment so I'm not sure how much I'll be able to help. Looking at the discord.js documentation, bot.reply should still be a function. Have you follwed the instructions to install discord.js?
